bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: /*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds

spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
